import { c as createComponent, m as maybeRenderHead, r as renderComponent, a as renderTemplate, e as renderScript, b as addAttribute } from './astro/server_C7Z2_luB.mjs';
import 'kleur/colors';
/* empty css                             */
import { c as clarityConfig } from './clarity.config_DRA55FFN.mjs';

const $$Search = createComponent(async ($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="relative" data-astro-cid-otpdt6jm> <button id="search-trigger" class="w-full flex items-center gap-2 px-3 py-2 text-sm text-muted-foreground bg-muted/50 rounded-md border border-border hover:border-primary transition-colors" data-astro-cid-otpdt6jm> <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" data-astro-cid-otpdt6jm> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" data-astro-cid-otpdt6jm></path> </svg> <span data-astro-cid-otpdt6jm>Search...</span> <kbd class="ml-auto px-2 py-0.5 text-xs bg-background border border-border rounded" data-astro-cid-otpdt6jm>⌘K</kbd> </button> </div> <!-- Search Modal - Portal to body level --> ${renderComponent($$result, "teleport-search-modal", "teleport-search-modal", { "data-astro-cid-otpdt6jm": true }, { "default": () => renderTemplate` <div id="search-modal" class="hidden fixed inset-0 z-[9999] overflow-y-auto" style="z-index: 9999 !important;" data-astro-cid-otpdt6jm> <div class="flex min-h-screen items-start justify-center p-4 pt-20" data-astro-cid-otpdt6jm> <div class="fixed inset-0 bg-background/80 backdrop-blur-sm" id="search-backdrop" data-astro-cid-otpdt6jm></div> <div class="relative w-full max-w-2xl bg-background border border-border rounded-lg shadow-lg" data-astro-cid-otpdt6jm> <div class="flex items-center gap-3 px-4 py-3 border-b border-border" data-astro-cid-otpdt6jm> <svg class="w-5 h-5 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor" data-astro-cid-otpdt6jm> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" data-astro-cid-otpdt6jm></path> </svg> <input id="search-input" type="text" placeholder="Search documentation..." class="flex-1 bg-transparent outline-none text-foreground placeholder:text-muted-foreground" autocomplete="off" data-astro-cid-otpdt6jm> <button id="search-close" class="text-muted-foreground hover:text-foreground" data-astro-cid-otpdt6jm> <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" data-astro-cid-otpdt6jm> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" data-astro-cid-otpdt6jm></path> </svg> </button> </div> <div id="search-results" class="max-h-[60vh] overflow-y-auto p-2" data-astro-cid-otpdt6jm> <div class="px-4 py-8 text-center text-muted-foreground" data-astro-cid-otpdt6jm>
Start typing to search...
</div> </div> </div> </div> ${renderScript($$result, "/home/runner/work/databridge/databridge/clarity/src/components/Search.astro?astro&type=script&index=0&lang.ts")} </div>` })}`;
}, "/home/runner/work/databridge/databridge/clarity/src/components/Search.astro", void 0);

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(cooked.slice()) }));
var _a;
const $$ThemeToggle = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate(_a || (_a = __template(["", '<button id="theme-toggle" type="button" class="relative inline-flex h-10 w-20 items-center rounded-full border-2 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 bg-border hover:bg-border/80" aria-label="Toggle theme"> <!-- Toggle Track --> <span class="sr-only">Toggle theme</span> <!-- Sliding Button with Icons --> <span id="toggle-slider" class="absolute inline-flex h-8 w-8 items-center justify-center rounded-full bg-primary shadow-lg transform transition-transform duration-200 ease-in-out translate-x-0.5"> <!-- Sun Icon (Shows when light mode is active) --> <svg id="sun-icon" class="h-5 w-5 text-primary-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"> <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"></path> </svg> <!-- Moon Icon (Shows when dark mode is active) --> <svg id="moon-icon" class="h-5 w-5 text-primary-foreground hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"> <path stroke-linecap="round" stroke-linejoin="round" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"></path> </svg> </span> </button> <script>\n    const updateToggle = () => {\n        const isDark = document.documentElement.classList.contains("dark");\n        const sunIcon = document.getElementById("sun-icon");\n        const moonIcon = document.getElementById("moon-icon");\n        const slider = document.getElementById("toggle-slider");\n        \n        if (isDark) {\n            // Dark mode: show moon icon, slide to right\n            sunIcon?.classList.add("hidden");\n            moonIcon?.classList.remove("hidden");\n            slider?.classList.remove("translate-x-0.5");\n            slider?.classList.add("translate-x-[2.625rem]"); // Move to right side\n        } else {\n            // Light mode: show sun icon, slide to left\n            sunIcon?.classList.remove("hidden");\n            moonIcon?.classList.add("hidden");\n            slider?.classList.remove("translate-x-[2.625rem]");\n            slider?.classList.add("translate-x-0.5");\n        }\n    };\n    \n    const handleToggleClick = () => {\n        const element = document.documentElement;\n        element.classList.toggle("dark");\n\n        const isDark = element.classList.contains("dark");\n        localStorage.setItem("theme", isDark ? "dark" : "light");\n        \n        updateToggle();\n    };\n\n    document\n        .getElementById("theme-toggle")\n        ?.addEventListener("click", handleToggleClick);\n    \n    // Initialize toggle state on page load\n    updateToggle();\n<\/script>'])), maybeRenderHead());
}, "/home/runner/work/databridge/databridge/clarity/src/components/ThemeToggle.astro", void 0);

const $$Header = createComponent(($$result, $$props, $$slots) => {
  const base = "/databridge-docs/";
  return renderTemplate`${maybeRenderHead()}<header class="fixed top-0 left-0 right-0 z-50 border-b border-border bg-background/80 backdrop-blur-md supports-[backdrop-filter]:bg-background/60"> <div class="flex h-16 items-center px-4 sm:px-6 lg:px-8"> <button id="sidebar-toggle" class="mr-4 md:hidden p-2 text-muted-foreground hover:text-foreground"> <span class="sr-only">Open sidebar</span> <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path> </svg> </button> <div class="flex items-center gap-2 font-bold text-xl tracking-tight"> <a${addAttribute(`${base}`, "href")} class="flex items-center gap-3 hover:opacity-80 transition-opacity"> <img${addAttribute(`${base}logo.svg`, "src")}${addAttribute(clarityConfig.site.name, "alt")} class="h-8 w-8"> <span class="text-foreground">${clarityConfig.site.name}</span> </a> </div> <div class="flex-1"></div> <div class="flex items-center gap-4"> ${renderTemplate`<div class="hidden md:block w-64"> ${renderComponent($$result, "Search", $$Search, {})} </div>`} <nav class="flex items-center gap-4"> ${clarityConfig.navigation.showLogin} ${renderTemplate`${renderComponent($$result, "ThemeToggle", $$ThemeToggle, {})}`} </nav> </div> </div> </header>`;
}, "/home/runner/work/databridge/databridge/clarity/src/components/Header.astro", void 0);

const $$Footer = createComponent(($$result, $$props, $$slots) => {
  (/* @__PURE__ */ new Date()).getFullYear();
  return renderTemplate`${maybeRenderHead()}<footer class="mt-20 border-t border-border py-8 text-sm text-muted-foreground"> <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> <div class="flex flex-col md:flex-row justify-between items-center gap-4"> <p>${clarityConfig.footer.copyright}</p> ${clarityConfig.footer.links.length > 0 && renderTemplate`<nav class="flex flex-wrap gap-6 justify-center"> ${clarityConfig.footer.links.map((link) => renderTemplate`<a${addAttribute(link.href, "href")} class="hover:text-foreground transition-colors"> ${link.text} </a>`)} </nav>`} </div> </div> </footer>`;
}, "/home/runner/work/databridge/databridge/clarity/src/components/Footer.astro", void 0);

export { $$Footer as $, $$Header as a };
